const FoodData = [
    {
      id: 1,
      img: "https://img.freepik.com/free-photo/seafood-pizza_74190-5944.jpg?w=996&t=st=1693062328~exp=1693062928~hmac=53fd9ad496580db41c6ca8066510cd89c6b0a0389de8bb6b875a78a1eda09cb5",
      name: "Onion Pizza",
      price: 150,
      desc: "A delicious pizza topped with fresh onions for a delightful flavor combination. This pizza is perfect for onion lovers and offers a unique twist on the classic pizza experience. Enjoy the perfect blend of cheesy goodness and the sharp taste of onions in every bite. Whether you're sharing with friends or enjoying it all to yourself, this Onion Pizza is sure to satisfy your pizza cravings.",
      category: "Lunch",
      rating: 4.5,
    },
    {
      id: 2,
      img: "https://assets-global.website-files.com/64931d2aee18510b47f4bb1f/65c3cdd12a6be3fb8cca3a33_dosa.jpeg",
      name: "Dosa",
      price: 130,
      desc: "Dosa is a giant crispy crepe. It is one of the most beloved breakfast items in South India. Dosa is a lacey thin crepe made with fermented rice and lentil batter.  ",
      category: "Breakfast",
      rating: 4.2,
    },
    {
      id: 3,
      img: "https://w7.pngwing.com/pngs/21/55/png-transparent-pepperoni-pizza-margarita-pizza-margherita-italian-cuisine-tomato-pizza-food-cheese-recipe-thumbnail.png",
      name: "Pepperoni Pizza",
      price: 160,
      desc: "Indulge in the savory delight of this Pepperoni Pizza, loaded with slices of spicy pepperoni, melted cheese, and a tangy tomato sauce. A popular choice that's perfect for satisfying your pizza cravings.",
      category: "Lunch",
      rating: 4.6,
    },
    {
      id: 4,
      img: "https://assets-global.website-files.com/64931d2aee18510b47f4bb1f/65c3cdd13038439038233631_Paratha.jpeg",
      name: "Paratha",
      price: 140,
      desc: "Paratha is golden-brown in color, crispy and flaky. This square-shaped unleavened flatbread is made with whole wheat flour, salt, water, and ghee. ",
      category: "Breakfast",
      rating: 4.2,
    },
    {
      id: 5,
      img: "https://w7.pngwing.com/pngs/843/171/png-transparent-pizza-73-restaurant-catupiry-chicken-as-food-pizza-baked-goods-food-recipe-thumbnail.png",
      name: "BBQ Chicken Pizza",
      price: 170,
      desc: "Savor the smoky goodness of this BBQ Chicken Pizza, featuring tender pieces of chicken marinated in barbecue sauce, red onions, and a medley of cheeses. A fusion of flavors that's sure to delight your taste buds.",
      category: "Lunch",
      rating: 4.8,
    },
    {
      id: 6,
      img: "https://w7.pngwing.com/pngs/133/54/png-transparent-pancakes-served-on-plate-banana-pancakes-scrambled-eggs-breakfast-ihop-pancake-food-recipe-eating-thumbnail.png",
      name: "Classic Pancakes",
      price: 80,
      desc: "Start your day with a stack of fluffy pancakes served with maple syrup and a dollop of butter. A timeless breakfast favorite that's sure to satisfy your morning cravings.",
      category: "Breakfast",
      rating: 4.5,
    },
    {
      id: 7,
      img: "https://assets-global.website-files.com/64931d2aee18510b47f4bb1f/65c3cdd126c4dfd0d8c45e58_Batata-Poha.jpeg",
      name: "Batata Poha",
      price: 110,
      desc: "Batata Poha is also known as flattened potato rice. This is a popular and quick Gujarati snack and breakfast item.  ",
      category: "Breakfast",
      rating: 4.2,
    },
    {
      id: 8,
      img: "https://w7.pngwing.com/pngs/683/103/png-transparent-frozen-yogurt-parfait-breakfast-yoghurt-fruit-salad-yogurt-frutti-di-bosco-food-breakfast-thumbnail.png",
      name: "Greek Yogurt Parfait",
      price: 95,
      desc: "Enjoy a healthy and refreshing breakfast with layers of creamy Greek yogurt, fresh berries, honey, and granola. A balanced option that provides a burst of flavors and energy.",
      category: "Breakfast",
      rating: 4.1,
    },
    {
      id: 9,
      img: "https://w7.pngwing.com/pngs/400/603/png-transparent-toast-tostytosty-la-tosteria-menu-food-dish-avocado-toast-food-toast-avocado-toast-thumbnail.png",
      name: "Avocado Toast",
      price: 120,
      desc: "Savor the creaminess of mashed avocado on toasted whole grain bread, topped with a sprinkle of sea salt and red pepper flakes. A trendy and nutritious breakfast choice.",
      category: "Breakfast",
      rating: 4.6,
    },
    {
      id: 10,
      img: "https://assets-global.website-files.com/64931d2aee18510b47f4bb1f/65c3cdd1525e361a3226e553_Khaman-Dhokla.jpeg",
      name: "Khaman Dhokla",
      price: 85,
      desc: "Dhokla is a savory, soft, and fluffy steamed chickpea flour cake. It can be served as breakfast or snack throughout the day, made from gram flour, semolina, and various spices.",
      category: "Breakfast",
      rating: 4.5,
    },
    {
      id: 11,
      img: "https://w7.pngwing.com/pngs/875/111/png-transparent-north-fish-seafood-dish-smoked-salmon-restaurant-grilled-fish-hd-soup-food-seafood-thumbnail.png",
      name: "Grilled Salmon",
      price: 190,
      desc: "Delight in a perfectly grilled salmon fillet seasoned with herbs and served with a side of roasted vegetables. A healthy and flavorful dinner option that's rich in omega-3 fatty acids.",
      category: "Dinner",
      rating: 4.5,
    },
    {
      id: 12,
      img: "https://w7.pngwing.com/pngs/756/828/png-transparent-taglierini-carbonara-fettuccine-alfredo-chicken-pasta-chicken-fillet-thumbnail.png",
      name: "Chicken Alfredo Pasta",
      price: 160,
      desc: "Indulge in creamy fettuccine Alfredo pasta with tender pieces of grilled chicken. This comforting dinner dish is a blend of pasta, rich Alfredo sauce, and savory chicken.",
      category: "Dinner",
      rating: 4.8,
    },
    {
      id: 13,
      img: "https://w7.pngwing.com/pngs/651/721/png-transparent-veggie-burger-vegetable-food-recipe-stir-frying-vegetables-frying-pan-frozen-vegetables-fruit-thumbnail.png",
      name: "Vegetable Stir-Fry",
      price: 130,
      desc: "Enjoy a medley of colorful vegetables stir-fried in a flavorful sauce, served over steamed rice. A light and nutritious dinner that's both satisfying and wholesome.",
      category: "Dinner",
      rating: 4.2,
    },
    {
      id: 14,
      img: "https://w7.pngwing.com/pngs/575/331/png-transparent-burrito-taco-bell-mexican-cuisine-chipotle-mexican-grill-menu-thumbnail.png",
      name: "Grilled Chicken Burrito Bowl",
      price: 160,
      desc: "Savor the flavors of a delicious burrito bowl with tender grilled chicken, black beans, rice, sautéed peppers and onions, shredded cheese, and a drizzle of zesty cilantro-lime dressing. A hearty and satisfying chicken dinner option.",
      category: "Dinner",
      rating: 4.6,
    },
    {
      id: 15,
      img: "https://w7.pngwing.com/pngs/47/171/png-transparent-chinese-noodles-hot-and-sour-soup-risotto-lomi-lamian-slippery-mushrooms-risotto-dusi-soup-food-recipe-thumbnail.png",
      name: "Mushroom Risotto",
      price: 175,
      desc: "Indulge in creamy and flavorful mushroom risotto, made with Arborio rice, sautéed mushrooms, and a touch of Parmesan cheese. A comforting and sophisticated dinner choice.",
      category: "Dinner",
      rating: 4.5,
    },
    {
      id: 16,
      img: "https://assets-global.website-files.com/64931d2aee18510b47f4bb1f/65c3cdd1a6314e83843fba45_Masala-Omelette.jpeg",
      name: "Masala Omelet",
      price: 120,
      desc: "Masala Omelet is no ordinary omelet, it is an elevated spicy omelet. It is loaded with onions, cilantro, green pepper, tomatoes, and a myriad of spices. ",
      category: "Breakfast",
      rating: 4.3,
    },
    {
      id: 17,
      img: "https://w7.pngwing.com/pngs/204/32/png-transparent-crispy-fried-chicken-karaage-chicken-nugget-chicken-fingers-buffalo-wing-carrot-chilli-thumbnail.png",
      name: "Crispy Chicken Wings",
      price: 130,
      desc: "Savor the satisfying crunch of crispy chicken wings seasoned to perfection. Choose your favorite sauce, from tangy BBQ to spicy buffalo, for a flavorful snacking experience.",
      category: "Snacks",
      rating: 4.4,
    }, 
    {
      id: 17,
      img: "https://assets-global.website-files.com/64931d2aee18510b47f4bb1f/65c3cd56047fe0a51f601006_Nimbo-Pani.jpeg",
      name: "Nimbo Pani",
      price: 130,
      desc: "“Nimbo” translates to “lemon” in Hindi, and “pani” means “water.” This is essentially the Indian version of lemonade. This cost-effective drink is made with freshly squeezed lemon juice, water, and sugar.  Sometimes, other ingredients such as mint leaves, black salt, or a pinch of roasted cumin are added for flavor.",
      category: "Drinks",
      rating: 4.4,
    },
    {
      id: 18,
      img: "https://w7.pngwing.com/pngs/816/163/png-transparent-grilled-skewered-meat-bakery-paneer-tikka-indian-cuisine-vegetarian-cuisine-cake-food-baking-cake-decorating-thumbnail.png",
      name: "Paneer Tikka Skewers",
      price: 130,
      desc: "Enjoy succulent pieces of marinated paneer (Indian cottage cheese) skewered and grilled to perfection. Served with mint chutney, these paneer tikka skewers offer a flavorful and aromatic Indian snack experience.",
      category: "Snacks",
      rating: 4.9,
    },
    {
      id: 19,
      img: "https://w7.pngwing.com/pngs/356/675/png-transparent-falafel-lebanese-cuisine-take-out-mediterranean-cuisine-hummus-bed-miscellaneous-furniture-food-thumbnail.png",
      name: "Hummus and Veggie Platter",
      price: 90,
      desc: "Relish the smooth and flavorful hummus accompanied by a variety of fresh vegetable sticks and pita bread. A nutritious and satisfying option for a light and refreshing snack.",
      category: "Snacks",
      rating: 4.4,
    },
    {
      id: 20,
      img: "https://w7.pngwing.com/pngs/435/847/png-transparent-pincho-canape-skewer-fruit-others-thumbnail.png",
      name: "Fruit Skewers",
      price: 70,
      desc: "Indulge in a colorful assortment of fruit skewers featuring juicy chunks of melon, berries, pineapple, and more. A sweet and refreshing snack that's both delicious and visually appealing.",
      category: "Snacks",
      rating: 4.8,
    },
    
    {
      id: 20,
      img: "https://assets-global.website-files.com/64931d2aee18510b47f4bb1f/65c3cd575cd3282278dcf312_Sugarcane-Juice.jpeg",
      name: "Sugarcane Juice",
      price: 70,
      desc: "Sugarcane juice, also known as ganna ka raas, is perhaps every Indian’s favorite street food drink. A glass of fresh sugarcane juice is a natural way to cool down during the blistering heat. Sugarcane juice is made by pressing sugarcane stalks through ",
      category: "Drinks",
      rating: 4.8,
    },
    
    {
      id: 20,
      img: "https://assets-global.website-files.com/64931d2aee18510b47f4bb1f/65c3cd56537ac8426e942d53_Falsa-Sherbet.jpeg",
      name: " Falsa Sherbet",
      price: 70,
      desc: "This delicious concoction is made from a rare and beloved seasonal fruit, Indian sherbet berry also known as falsa. Fresh Indian sherbet berries are hard to find in the Un",
      category: "Drinks",
      rating: 4.8,
    },
  ];
  export default FoodData;